# Generated by Django 3.1.7 on 2021-03-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify_me_bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busses',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bussesusers',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='currentbussesroutechanges',
            options={'managed': False},
        ),
    ]
