# Generated by Django 3.0.6 on 2020-05-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyMunicipalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notify_municipalities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotifyMunicipalitiesUsers',
            fields=[
                ('municipality_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'notify_municipalities_users',
                'managed': False,
            },
        ),
    ]
